### PR TITLE
更新英文wiki中关于星云介绍的内容

### PR DESCRIPTION
**Pull request by weiht12**
更新英文wiki中关于星云介绍的内容

### CODE REVIEW

**Comment by CrisBRM** [comment]
Again, wrong article..?

**Comment by weiht12** [comment]
OK，What nebulas This section on NR/NI/NF is a duplicate of the contents of the Autonomous Metanet directory, so the content has been replaced accordingly.

**Comment by weiht12** [comment]
### **What nebulas This section on NR/NI/NF is a duplicate of the contents of the Autonomous Metanet directory, so the content has been replaced accordingly.**

**Comment by weiht12** [comment]
@CrisBRM

**Comment by Woo-ing** [comment]
@weiht12 Change the file name and commit again。

**Pull request closed without merging**
