### PR TITLE
faq.md

### PR DESCRIPTION
**Pull request by arielsbecker**
Regarding this PR, I had to comment the last section out because it doesn't seems to be ready to publish yet; also, the ToC didn't mention that section either.

### CODE REVIEW

**Comment by neealwen** [comment]
hi, this  is Neal from Nebulas, which PR you mentioned above?

**Comment by arielsbecker** [comment]
Sorry, my bad. By PR I meant “this file”; that is, faq.md. The original has what it looks like some added lines at the bottom that, IMO, aren't meant to be published yet, thus I commented out those lines.

**Comment by neealwen** [comment]
do you mean the smart contract ide part?

**Comment by arielsbecker** [comment]
No, “binary storage” (and all the subsections below it). It seemed a little bit off compared to the rest of the FAQ, and since it wasn't listed on the ToC, I though it was added after published.

**Comment by arielsbecker** [comment]
Oh, I did the entire translation anyways, so I'll close this PR and start a new one, with the fully-translated file.

**Pull request closed without merging**
